### ISSUE TITLE
not working on windows

### ISSUE THREAD

**Issue by pwelter34** [fabiospampinato/vscode-optimize-images#5]
I'm trying to get this to work with [pingo](https://css-ig.net/pingo).  I right click on an image and nothing happens.  Is there a way to output the command its trying to run?

Settings

```json
{
    "optimizeImages.app": "D:\\Downloads\\pingo\\pingo.exe",
    "optimizeImages.appOptions": [
        "-s8", 
        "-pngpalette=79", 
        "[filepath]"
    ],
    "optimizeImages.imageRegex": ".*\\.(png|jpe?g)$"
}
```

**Comment by fabiospampinato** [comment]
[This](https://github.com/sindresorhus/opn/blob/56798ff3a2ddc4019e6dd6fe5219230ddd32bb78/index.js#L76
) is the line that is supposed to spawn the app.

Maybe `opn` is adding an extra `.exe` [here](https://github.com/sindresorhus/opn/blob/master/index.js#L34), are you using WSL?

Or maybe this argument: `"-pngpalette=79"` should be split into `"-pngpalette"` and `"79"` 🤔 

What's an equivalent command that you can execute from the command line that works? 

Also how do I download pingo? If I'll find the time for this I'd like to reproduce the problem.

**Comment by pwelter34** [comment]
pingo can be download here <https://css-ig.net/pingo>.  This is the tool Image Optimizer for Visual Studio uses.  <https://github.com/madskristensen/ImageOptimizer>

Command line syntax is 

```shell
D:\Downloads\pingo\pingo.exe -s8 -pngpalette=79 Diagram.png
```

**Comment by fabiospampinato** [comment]
> pingo can be download here https://css-ig.net/pingo.

I can't see any downloads button or anything like that, maybe it's hidden on non-Windows systems 🤷‍♂️ 

Let me know when you tried my suggestions for potentially fixing the problem.

**Comment by pwelter34** [comment]
I put the program in the system path and simplified the settings.  Still doesn't work. 

```json
{
    "optimizeImages.app": "pingo",
    "optimizeImages.appOptions": [
        "[filepath]"
    ],
    "optimizeImages.imageRegex": ".*\\.(png|jpe?g)$"
}
```

**Comment by fabiospampinato** [comment]
Sorry I don't have the time to try out pongo, try using this instead: #8
