### ISSUE TITLE
Alternative to ImageOptim for Linux

### ISSUE THREAD

**Issue by stefano-b** [fabiospampinato/vscode-optimize-images#6]
I'd like to suggest Trimage as a Linux based alternative to ImageOptim.

https://github.com/Kilian/Trimage

https://trimage.org/

**Comment by fabiospampinato** [comment]
@stefano-b That's a good suggestion, thanks. Would you like to submit a PR for updating the readme accordingly?

**Comment by fabiospampinato** [comment]
It looks like Trimage is already mentioned in the readme right now.
