### ISSUE TITLE
IOptimizer for windows

### ISSUE THREAD

**Issue by ymg2006** [fabiospampinato/vscode-optimize-images#8]
add this repo for as windows optimizer , tested working , mainly written for vscode-optimize-images
<a href="vscode-optimize-images">https://github.com/ymg2006/Image-Optimizer </a>
compiled download link is <a href="https://ci.appveyor.com/project/ymg2006/image-optimizer/build/artifacts">IOptimizer</a>

**Comment by fabiospampinato** [comment]
Sorry for the late reply.

Seems cool, thanks! Can you submit a PR for linking to it in our readme in the recommended apps for Windows section?

**Comment by ymg2006** [comment]
Hi again ,
PR is added, please accept , thanks in advance
